import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

import SmoothScrollProvider from '@/components/providers/SmoothScrollProvider';
import TopBar from '@/components/TopBar';
import Background from '@/components/ui/Background';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Anddy Labrut',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
      >
        <NextIntlClientProvider messages={messages}>
          <SmoothScrollProvider>
            <Background
              className="size-full"
              gradient={{
                display: true,
                colorStart: 'rgba(0, 125, 100, 0.65)',
                colorEnd: 'rgba(15, 15, 15, 1)',
                radius: 600,
                opacity: 1,
              }}
              dots={{
                display: true,
                color: 'rgba(255, 255, 255, 0.95)',
                radius: 3,
              }}
              lines={{
                display: true,
                color: 'rgba(255, 255, 255, 0.5)',
              }}
            />
            <TopBar />
            {children}
          </SmoothScrollProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
